name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm destruction'
        required: true
        default: 'no'

permissions:
  contents: read

jobs:
  terraform_static_analysis:
    name: 'Terraform Static Analysis'
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform_static_analysis
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirmation == 'yes'
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure AWS Credentials (use v4 for consistency)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.LOCATION }}

      # Terraform Destroy Step
      - name: Terraform Destroy
        working-directory: ./terraform  # Adjust if necessary
        run: |
          pwd
          ls -la  
          terraform init  
          terraform destroy --auto-approve